### ISSUE TITLE
Policy containing Host Factory breaks all modifications

### ISSUE THREAD

**Issue by hughsaunders** [eranha/conjur-enchanter#2]
If the currently loaded policy contains a host factory, then all modifications (eg create user) will fail with an exception (see below for stack trace).

Steps to reproduce:

1. Deploy empty conjur oss via [conjur quick start](https://github.com/cyberark/conjur-quickstart)
2. Login with Enchanter (I'm using ba888ac3fa3fd586199255ce651d3505720c2482)
3. Create a user (creating a policy doesn't work when theres no root policy, but creating a user implicitly creates the root policy)
4. Create the host factory policy shown below
5. Try and create another user (this fails with the stack trace shown below). 

```
- !policy
  id: policy2
  owner: !policy root
  body:
   - !layer
     id: test-layer
   - !host-factory
     id: test
     layers: test-layer
     annotations:
       test: test
```

```14:49:48.492 [AWT-EventQueue-0] TRACE com.cyberark.resource.RestApiResourceProvider - get(url=http://localhost:8080/resources/conjur) exit return response length: 2769
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: No enum constant com.cyberark.models.ResourceType.host_factory
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at com.cyberark.models.ResourceType.valueOf(ResourceType.java:3)
	at com.cyberark.models.ResourceIdentifier.fromString(ResourceIdentifier.java:74)
	at com.cyberark.resource.ResourcesServiceImpl.lambda$getResourceIdentifiers$10(ResourcesServiceImpl.java:695)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:1003)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at com.cyberark.resource.ResourcesServiceImpl.getResourceIdentifiers(ResourcesServiceImpl.java:697)
	at com.cyberark.resource.ResourcesServiceImpl.getResourceIdentifiers(ResourcesServiceImpl.java:681)
	at com.cyberark.actions.NewResourceAction.actionPerformed(NewResourceAction.java:92)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6626)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3389)
	at java.desktop/java.awt.Component.processEvent(Component.java:6391)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5001)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4833)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:746)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:744)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:743)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Thanks very much for your work on this tool, it has much potential :)

**Comment by eranha** [comment]
Fixed.
